name: MySchool 👌

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore
        run: dotnet restore ./MySchool.sln

      - name: Build
        run: dotnet build ./MySchool.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./MySchool.sln --configuration Release --no-build
